name: build and deploy code

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_HOSTNAME: 127.0.0.1
      DATABASE_PORT: 3306
      DATABASE_NAME: api_test
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: ""
      SECRET_KEY: dummy
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Install pytest
        run: pip install pytest 

      - name: Run tests
        run: pytest tests/test_posts.py --disable-warnings -v -s
        env:
          PYTHONPATH: ${{ github.workspace }}
          DATABASE_HOSTNAME: 127.0.0.1
          DATABASE_PORT: 3306
          DATABASE_NAME: api_test
          DATABASE_USERNAME: root
          DATABASE_PASSWORD: ""
